services:
  - type: web
    name: techsanta-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start

  - type: web
    name: techsanta-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
