services:
  # Backend API Service
  - type: web
    name: techsanta-backend
    env: node
    region: oregon
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        sync: false
      - key: MONGO_URL
        sync: false

  # Frontend Static Site
  - type: web
    name: techsanta-frontend
    env: static
    region: oregon
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        sync: false
